### PR TITLE
uploading hero file for issue #7

### LINKED ISSUE #7: Change Hero Image to a more suitable one for Opencode

### PR DESCRIPTION
**Pull request by PratyushPareek**
__7__ 

Fixes #7 

#### Short description of what this resolves:

uploading a hero image

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Live link pls.

**Comment by PratyushPareek** [comment]
The image is edited
Should I provide link for the original image?

**Comment by abhishekmsingh** [comment]
For generating live link,go to your repository settings, scroll down to github pages section and select master branch in the sources. The url you get just give us that.

**Comment by PratyushPareek** [comment]
https://pratyushpareek.github.io/Opencode-Collaborative-20/

**Comment by thesmallstar** [comment]
@PratyushPareek  it is expected you also implement the image not just add it.

**Comment by ekanban** [comment]
@PratyushPareek updates?

**Comment by ekanban** [comment]
@PratyushPareek I'll have to close this PR due to inactivity. Please respond.

**Comment by PratyushPareek** [comment]
I'm very sorry for the inactivity
I would still like to work on this task and will get to it asap
Although if I've missed the deadline, and protocol dictates my claim moot,
I'll accept it and work on something else

**Pull request closed without merging**
