### PR TITLE
Added footer

### LINKED ISSUE #371: Create Footer
The current footer looks really bad. Add a cool footer and link all the social networks within it.
Make sure alignment is proper in every resolution

### PR DESCRIPTION
**Pull request by Cybertron-Avneesh**
__371__ 

Fixes #371 

#### Short description of what this resolves:
Created footer 
https://cybertron-avneesh.github.io/OpencodeFavIcon/

image

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Jigar3** [comment]
Give proper padding and use some other color for footer background, something that matches with the website

**Comment by Cybertron-Avneesh** [comment]
@Jigar3 Sir i have updated footer 
https://cybertron-avneesh.github.io/OpencodeFavIcon/

**Comment by Jigar3** [comment]
Still there isn't enough padding 
Screenshot from 2020-02-13 20-28-21

**Comment by Cybertron-Avneesh** [comment]
Sir you mean padding for the social icons at top

**Comment by Cybertron-Avneesh** [comment]
https://cybertron-avneesh.github.io/OpencodeFavIcon/

**Comment by thesmallstar** [comment]
@Cybertron-Avneesh  some padding at the bottom too.

**Comment by Jigar3** [comment]
Screenshot from 2020-02-13 22-32-13

You have applied padding only on the top and not towards the bottom

**Comment by Cybertron-Avneesh** [comment]
Done sir 
https://cybertron-avneesh.github.io/OpencodeFavIcon/

**Comment by Jigar3** [comment]
The footer is not very responsive. Only mobile resolution things can be improved.

Screenshot from 2020-02-14 02-54-29

**Comment by Cybertron-Avneesh** [comment]
Made footer more responsive.
Now on hover social icons get highlighted.
https://cybertron-avneesh.github.io/OpencodeFavIcon/
image

**Pull request merged**
