### PR TITLE
Added My Website

### PR DESCRIPTION
**Pull request by Cybertron-Avneesh**
__274__ 

#274 
#### Short description of what this resolves:
Created my website

https://cybertron-avneesh.github.io/My-Website/

#### Changes proposed in this pull request and/or Screenshots of changes:
websitepage1

websitepage2

-
-
-

### CODE REVIEW

**Comment by Jigar3** [comment]
@Cybertron-Avneesh Live-link?

**Comment by Cybertron-Avneesh** [comment]
Sir @Jigar3  https://cybertron-avneesh.github.io/My-Website/

**Comment by Jigar3** [comment]
Also, there are unnecesary new lines within the file. Remove them.

**Comment by Cybertron-Avneesh** [comment]
@Jigar3 resolved conflicts

**Pull request merged**
