### PR TITLE
#5 displayed participant list and their details

### LINKED ISSUE #5: Add participants Section
Fetch Data from participants.json 
It should display the name and most of the information in JSON.

### PR DESCRIPTION
**Pull request by kavi-12**
__5__ 

Fixes #5 

#### Short description of what this resolves:

Displayed the complete details of participants on the index.html as updated in participants.json

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Live link?

**Comment by kavi-12** [comment]
https://kavi-12.github.io/Opencode-Collaborative-20/


live link

**Comment by thesmallstar** [comment]
Expected in form of photo tiles, with there name written below the photos. Similar to project section. 4-5 in a row.

**Comment by kavi-12** [comment]
displayed in the form of photo card

**Comment by thesmallstar** [comment]
Looks great! will be merged as soon as the particiapnt.json is fixed.

**Comment by thesmallstar** [comment]
squash the commits till then ;)

**Comment by ekanban** [comment]
@thesmallstar the same participants are being rendered multiple times. Is it because of the participants.json issue?

**Comment by thesmallstar** [comment]
@Ace-Bansal yes, I have made an issue for it,

**Comment by zerefwayne** [comment]
@kavi-12 Updates? It would be better if you can do it quickly as this is an urgent issue.

**Comment by kavi-12** [comment]
I already did it few days ago and the live link is in the comment section above


https://kavi-12.github.io/Opencode-Collaborative-20/

**Comment by thesmallstar** [comment]
@kavi-12 sorry for the delay, we have fixed the JSON. 
Can you just solve the conflicts now I will merge it?

**Comment by kavi-12** [comment]
@thesmallstar  the conflicts are resolved

**Comment by thesmallstar** [comment]
Great work!

**Pull request merged**
