### PR TITLE
Made button links open in new tab

### LINKED ISSUE #281: Project repository link should open in new tab
When you click on the Project Repository button, it should open in a new tab.

image

### PR DESCRIPTION
**Pull request by starboi02**
__281__ 

Fixes #281 

#### Short description of what this resolves:

Project repository link opens in new tab.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by starboi02** [comment]
@NitinMadhukar please review

**Comment by starboi02** [comment]
@zerefwayne please review

**Comment by starboi02** [comment]
@ujjwal-batra please review

**Comment by ujjwal-batra** [comment]
@starboi02 live link?

**Comment by starboi02** [comment]
https://starboi02.github.io/

**Comment by starboi02** [comment]
https://starboi02.github.io/

**Comment by starboi02** [comment]
@ujjwal-batra https://starboi02.github.io/

**Comment by starboi02** [comment]
@NitinMadhukar please review

**Pull request merged**
