### PR TITLE
Added todo list gh page link

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__329__ 

#### Short description of what this resolves:

Added todo list gh page link

#### Changes proposed in this pull request and/or Screenshots of changes:

https://untrulynoxiusmj.github.io/toDo/

### CODE REVIEW

**Comment by tushparte** [comment]
fix merge conflicts

**Comment by untrulynoxiusmj** [comment]
@niftyy  done

**Comment by tushparte** [comment]
squash

**Comment by untrulynoxiusmj** [comment]
@niftyy how to squash the commit done by resolving conflict
it doesn't appear there when i try to squash

**Comment by untrulynoxiusmj** [comment]
@NitinMadhukar please review

**Pull request closed without merging**
