### PR TITLE
timer

### LINKED ISSUE #291: Add a timer above hero image
It should show the number of days hours and seconds left.

### PR DESCRIPTION
**Pull request by pradhuman1**
__291__ 

Fixes #291  

#### Short description of what this resolves:
Timer Added

#### Changes proposed in this pull request and/or Screenshots of changes:

-https://pradhuman1.github.io/Opencode-Collaborative-20/
-
-

### CODE REVIEW

**Comment by Jigar3** [comment]
give more padding at the top and use colons to distinguish day: hour: minute. The current implementation is hard on the eyes

**Comment by pradhuman1** [comment]
@Jigar3 review now

**Comment by Jigar3** [comment]
The mobile version is aligned pretty badly, make this timer mobile friendly

**Comment by pradhuman1** [comment]
@Jigar3 please review now

**Comment by Jigar3** [comment]
Screenshot from 2020-02-13 22-33-31

Still isn't mobile friendly

**Comment by thesmallstar** [comment]
Why did you remove the original hero image?

**Comment by pradhuman1** [comment]
@Jigar3 please review now

**Comment by pradhuman1** [comment]
@Jigar3 please Review now

**Comment by Jigar3** [comment]
squash your commits

**Comment by pradhuman1** [comment]
@Jigar3 commit squashed please review

**Pull request merged**
