### PR TITLE
added card and aligned project section

### LINKED ISSUE #370: Edit the OpenCode Project Section
The Projects are miserably aligned and no structure is there.
Align the contents properly and enclose them within a card.

Some sample card designs are attached for reference.
Screenshot from 2020-02-12 19-31-21
Screenshot from 2020-02-12 19-31-07

### PR DESCRIPTION
**Pull request by blaze-assault**
__370__ 

Fixes #370

#### Short description of what this resolves:
added cards and aligned projects section

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by blaze-assault** [comment]
@Jigar3 @thesmallstar    please review

**Comment by Jigar3** [comment]
Live link?

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/Opencode-Collaborative-20a/

please review  @Jigar3

**Comment by Jigar3** [comment]
Make the icon appear on a seperate line and project name on line below that. Remove excess padding between the elements in the card. Use a onHover effect on each card. Currently, hovering doesn't do anything. Probably you can make a hover effect in which on hovering the box shadow becomes prominenet. The hover effect on Project Repository button is always not very good improve that

Screenshot from 2020-02-14 10-10-25

**Pull request closed without merging**
