### PR TITLE
Added NavDrawer

### LINKED ISSUE #171: Add a navigation drawer
put all the nav bar items in the navigation drawer

### PR DESCRIPTION
**Pull request by shuba400**
__171__ 

Fixes #171 Adds navigation drawer

#### Short description of what this resolves:
At first the navigation drawer collapsed to navigation drawer when screen size was small
But now the navigation drawer is offered through out.

#### Changes proposed in this pull request and/or Screenshots of changes:

-Changed the Navigation Bar from horizontal to vertical
-Help needed in beatifying drop down menu
-

### CODE REVIEW

**Comment by NitinMadhukar** [comment]
@shuba400  put the drawer on the right side and share the live link

**Comment by shuba400** [comment]
I am not able to change the direction of dropdown menu from right side.
So dropdown menu which is supposed to open at right side tends to get opened outside the boundry area(outside the screen of laptop, hence not visible)

**Comment by NitinMadhukar** [comment]
share the live link

**Comment by shuba400** [comment]
https://shuba400.github.io/Opencode-Collaborative-20/
The live link

**Comment by NitinMadhukar** [comment]
@shuba400 put the drawer on the right side and on cicking menu, the menu icon  should disapper and resolve conflicts

**Comment by shuba400** [comment]
update- shifted navdrawer to right and made a said changes on the menu option

**Comment by shuba400** [comment]
Sir please review the task

**Comment by NitinMadhukar** [comment]
@shuba400 Resolve conflicts

**Comment by shuba400** [comment]
It seems like I need to make a new PR with newer format in order to resolve conflicts

**Pull request closed without merging**
