### PR TITLE
Resume

### PR DESCRIPTION
**Pull request by ankit4284**
__187__ 

Fixes #187 

#### Short description of what this resolves:
Added my github resume

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thenullterminator** [comment]
@ankit4284 resolve conflicts and squash

**Comment by ankit4284** [comment]
@thenullterminator resolved conflicts and squashed. Please review.

**Comment by ankit4284** [comment]
@thenullterminator @thesmallstar plz review

**Comment by abhishekmsingh** [comment]
@ankit4284  the commits have not been squashed

**Pull request closed without merging**
