### PR TITLE
added myself as participant

### PR DESCRIPTION
**Pull request by padityak79**
__1__

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Archies11** [comment]
Mention the issue number

**Comment by Ace-Bansal** [comment]
mention issue number in the PR please!

**Comment by padityak79** [comment]
did it sir

**Comment by NitinMadhukar** [comment]
@padityak79 don't do multiple commits from next time and try to resolve conflicts yourself

**Pull request merged**
