### PR TITLE
js-game

### PR DESCRIPTION
**Pull request by prince-7**
__266__ 

#266

#### Short description of what this resolves:
new pull request for js game

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Jigar3** [comment]
live link of the game?

**Comment by prince-7** [comment]
> live link of the game?
https://prince-7.github.io/

**Comment by Jigar3** [comment]
Remove the word fixes from PR description. It will close the issue

**Comment by prince-7** [comment]
> Remove the word fixes from PR description. It will close the issue

done

**Pull request merged**
