### PR TITLE
made buttons to open in new tab 

### LINKED ISSUE #281: Project repository link should open in new tab
When you click on the Project Repository button, it should open in a new tab.

image

### PR DESCRIPTION
**Pull request by kumarmanish03**
__281__ 

Fixes #281 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by kumarmanish03** [comment]
please review my pr

**Comment by kumarmanish03** [comment]
https://manish-kumar-2000.github.io/Opencode20/

this is website

**Comment by thesmallstar** [comment]
repo not updated, perform git pull upstream master.

**Comment by starboi02** [comment]
@thesmallstar I claimed #281 first so its to be assigned to me. How is he making pr of this task?

**Pull request closed without merging**
