### PR TITLE
Added participant info

### PR DESCRIPTION
**Pull request by TamoghnoBhattacharya**
__1__ 

Fixes #1 

#### Short description of what this resolves:
I have added my info in the required format. Please look into it.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
wrong JSON format please recheck

**Comment by TamoghnoBhattacharya** [comment]
Made the changes sir please review

**Comment by thesmallstar** [comment]
You are removing data of other participants, Run 
git pull upstream master --rebase
git push

**Comment by ekanban** [comment]
I've fixed it for now. Please be careful in the future @TamoghnoBhattacharya

**Comment by TamoghnoBhattacharya** [comment]
Thanks a lot sir. I'll do it next time sure!

**Pull request merged**
