### PR TITLE
attached game created by me

### PR DESCRIPTION
**Pull request by blaze-assault**
__266__ 

task #266

#### Short description of what this resolves:
attached my game link.(learnt a lot for creating it).

#### Changes proposed in this pull request and/or Screenshots of changes:

-https://blaze-assault.github.io/game/color.html
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
Is this made by you?
__?__

**Comment by blaze-assault** [comment]
Sir yes that is created only by me i have not copied it  from anywhere.but yes i learnt a type of game like this in a udemy course in my  winter vac but that time i did not create it .i  started to create it day before yesterday .and i really invested a lot of time and efforts in it .and i can explain each and every line of code

**Comment by thesmallstar** [comment]
@blaze-assault 
I find your game highly similar to [this ](https://codepen.io/ogre14t/pen/JEBQXz) ( also the code), 
I will be reverting points for this PR, also a warning not to directly COPY CODE.
 You can make another PR, for the game to get points.

**Comment by blaze-assault** [comment]
I have not copied it .and i told you sir i have learnt it from a tutorial
but created it afterwards.the tutorial was from udemy whose link was given
to us during 30doc  in webd channel....but i have not copied it from
codepen or anywhere else .i have written each line of code by myself though
after learning you can revert the points .i will create another thing s

**Comment by blaze-assault** [comment]
Sir if you can revert points for a pr then please help me get those points
for which my pr was merged but i did not get points..
One is in interactive app channel of 20 points and one is of
opencode-collaborative-theapp repo of 10 points

**Comment by thesmallstar** [comment]
Don't worry. I am taking a team opinion on this, won't make a final decision on my own.

**Pull request merged**
