### PR TITLE
Tdo

### LINKED ISSUE #329: Make a todo list
use html, css, javascript and make a simple todo list having an add and remove button.
add a gh pages link to the list in list.md file, the list should be made after open code started.

### PR DESCRIPTION
**Pull request by pradhuman1**
__329__ 

Fixes #329 

#### Changes proposed in this pull request and/or Screenshots of changes:

-https://pradhuman1.github.io/Todo-Opencode/
-
-

### CODE REVIEW

**Comment by pradhuman1** [comment]
Sir i didnt get points @Jigar3

**Comment by Jigar3** [comment]
@thesmallstar

**Comment by pradhuman1** [comment]
What to do sir?? @Jigar3

**Comment by Jigar3** [comment]
Mil jaayenge bhai. Chill maro aur dusra issue code karo

**Comment by pradhuman1** [comment]
@abhiandthetruth

**Pull request merged**
