### PR TITLE
TIMER

### LINKED ISSUE #291: Add a timer above hero image
It should show the number of days hours and seconds left.

### PR DESCRIPTION
**Pull request by pradhuman1**
__291__ 

Fixes #291 

#### Short description of what this resolves:

Timer added

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/Opencode-Collaborative-20/

**Comment by ujjwal-batra** [comment]
@pradhuman1 resolve conflicts

**Comment by pradhuman1** [comment]
@ujjwal-batra conflicts resolved please review now

**Comment by pradhuman1** [comment]
@ujjwal-batra review

**Comment by pradhuman1** [comment]
@thesmallstar review

**Comment by Jigar3** [comment]
@pradhuman1 live link doesn't work

**Pull request closed without merging**
