### PR TITLE
Remove duplicate project section and add remaining projects

### LINKED ISSUE #217: Project section correction
1. Remove the top project section(there are two)
2. align the bottom project section for mobile view and desktop view
3.  add remaining projects,

### PR DESCRIPTION
**Pull request by sggts04**
__217__ 

Fixes #217

#### Short description of what this resolves:
Removes the duplicate project section and add remaining projects

#### Changes proposed in this pull request and/or Screenshots of changes:
Live Link: https://tired-authority.surge.sh/

### CODE REVIEW

**Comment by thesmallstar** [comment]
Squash.

**Comment by thesmallstar** [comment]
um?
image

image

**Comment by sggts04** [comment]
@thesmallstar fixed mobile look and squashed commits

**Comment by sggts04** [comment]
@thesmallstar please review

**Comment by thesmallstar** [comment]
Great!

**Pull request merged**
