### PR TITLE
Footer

### LINKED ISSUE #2: Create a footer for the website
Things required in the footer:

Logos of IIITA and GeekHaven on the left side.
OpenCode's social media links in the center-> [Facebook](https://www.facebook.com/opencodeiiita/), [Twitter](https://twitter.com/teamOpencode/) and [GitHub](https://github.com/opencodeiiita).
OpenCode's logo on the right side.

### PR DESCRIPTION
**Pull request by garvitchittora**
__2__ 

Fixes #2

#### Short description of what this resolves:
footer added with change in html and css code

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by garvitchittora** [comment]
https://garvitchittora.github.io/Opencode-Collaborative-20/

**Comment by abhishekmsingh** [comment]
@garvitchittora use images without background in the footer, the image background color mismatches the footer color. You should keep these things in mind whenever you style.

**Comment by garvitchittora** [comment]
sir , now what i am supposed to do?

**Comment by garvitchittora** [comment]
sir , my pr is not merged till now..

**Comment by abhishekmsingh** [comment]
The footer is not up to the mark. Please improve your footer and give an update within a day otherwise the issue will be assigned to another person.

**Comment by garvitchittora** [comment]
sir , what new changes you want .

**Comment by abhishekmsingh** [comment]
Refer to the above comment regarding the icons. You can implement that.

**Comment by zerefwayne** [comment]
@garvitchittora Send a separate Pull request from another branch for GitHub Resume. Also, the live link you provided is not working.

**Comment by garvitchittora** [comment]
1.
Screenshot (39)
2.
Screenshot (40)
3.
Screenshot (41)

sir,which one you like .
Sir if you are still not satisfied with these three, then can you please guide me the direction in which i should be working upon in order to make it better. I have been thinking on it for the past 2 days. 
Thanks

**Comment by abhishekmsingh** [comment]
Give me a live link. The link above isn't working.

**Comment by garvitchittora** [comment]
Sir , but from above three pic which theme is final .plz comment.

**Comment by abhishekmsingh** [comment]
The all white one looks fine to me. Just arrange the logo symmetrically.

**Pull request closed without merging**
