### PR TITLE
footer added

### LINKED ISSUE #2: Create a footer for the website
Things required in the footer:

Logos of IIITA and GeekHaven on the left side.
OpenCode's social media links in the center-> [Facebook](https://www.facebook.com/opencodeiiita/), [Twitter](https://twitter.com/teamOpencode/) and [GitHub](https://github.com/opencodeiiita).
OpenCode's logo on the right side.

### PR DESCRIPTION
**Pull request by garvitchittora**
__2__ 

Fixes #2

#### Short description of what this resolves:
Added footer with image of various sites like github , IIITA,opencode ,etc.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
live link?

**Comment by thesmallstar** [comment]
What is this?
image

**Comment by garvitchittora** [comment]
https://garvitchittora.github.io/Opencode-Collaborative-20/

**Comment by garvitchittora** [comment]
> What is this?
> image

this line was already present

**Comment by thesmallstar** [comment]
Can you improve it?
Look more footer styles on the internet.
Also remove all those lines I pointed earlier.

**Comment by garvitchittora** [comment]
ok sir

**Comment by garvitchittora** [comment]
But sir i think it is good style .

**Comment by garvitchittora** [comment]
i had deleted those lines.

**Comment by thesmallstar** [comment]
Live link  is not working.

**Comment by thesmallstar** [comment]
image
 remove this all

**Comment by garvitchittora** [comment]
https://garvitchittora.github.io/Opencode-Collaborative-20/

**Comment by garvitchittora** [comment]
sir , till jow my pr is not merged .

**Pull request closed without merging**
