### PR TITLE
changed hero image

### LINKED ISSUE #7: Change Hero Image to a more suitable one for Opencode

### PR DESCRIPTION
**Pull request by blaze-assault**
__7__ 

Fixes #7

#### Short description of what this resolves:
changed hero image.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/Opencode-Collaborative-20-1/

here is the live link .
@NitinMadhukar @abhiandthetruth 
please review the pr.

**Comment by blaze-assault** [comment]
@thesmallstar  please review

**Comment by blaze-assault** [comment]
@thesmallstar  please review

**Comment by blaze-assault** [comment]
@Jigar3  please review the pr

**Comment by Jigar3** [comment]
@blaze-assault LGTM

**Pull request merged**
