### PR TITLE
Added profile website

### PR DESCRIPTION
**Pull request by sggts04**
__274__ 

#274

#### Short description of what this resolves:
https://shreyasgupta.in/opencode-web/

### CODE REVIEW

**Comment by thesmallstar** [comment]
image

um?

**Comment by sggts04** [comment]
it is supposed to be that way in mobile view

**Comment by sggts04** [comment]
@thesmallstar new mobile site is up

**Comment by thesmallstar** [comment]
Just wondering, why do you have Jquery included?
image

**Comment by sggts04** [comment]
I just included all the bootstrap dependancies when making the initial structure. And this may not be the final form the website so I kept it in if I need it in the future @thesmallstar

**Pull request merged**
