### PR TITLE
Add Mentors section

### LINKED ISSUE #6: Add Mentors Section
Fetch mentors from mentors.json

### PR DESCRIPTION
**Pull request by sggts04**
__6__ 

Fixes #6 

#### Short description of what this resolves:
**I followed the same card style that the participant section had**

#### Changes proposed in this pull request and/or Screenshots of changes:
Live Link: https://jealous-pig.surge.sh/

P.S.: You guys really need to add yourself to mentors.json :P

### CODE REVIEW

**Comment by Jigar3** [comment]
Use  a proper card structure to display information. Use the same as https://github.com/opencodeiiita/Opencode-Collaborative-20/pull/399. Also create a link in the navbar for the same.

**Comment by sggts04** [comment]
@Jigar3 Done

image

image

**Comment by Jigar3** [comment]
Use a on hover effect on the card as well

**Comment by sggts04** [comment]
@Jigar3 done, hard refresh and check please.

**Comment by sggts04** [comment]
@Jigar3 @thesmallstar please review

**Comment by Jigar3** [comment]
Change the heading to "Mentors" and align it in the center with some padding at the top

**Comment by sggts04** [comment]
@Jigar3 done

**Comment by sggts04** [comment]
squashed @Jigar3

**Pull request merged**
