### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by Rohini13**
__3__

Fixes #ISSUENUMBER

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Rohini13** [comment]
Screenshot (34)
Screenshot (35)


live link: https://rohini13.github.io/Opencode-Collaborative-20/

**Comment by ekanban** [comment]
Change the background please. Also, don't remove the navbar.

**Comment by Rohini13** [comment]
Changed background. Added navigation bar.
Screenshot (37)

**Comment by ekanban** [comment]
Looks really good, nice job!
@thesmallstar @zerefwayne thoughts?

**Comment by thesmallstar** [comment]
Looks Great!

**Pull request merged**
