### PR TITLE
added cards in project section

### LINKED ISSUE #370: Edit the OpenCode Project Section
The Projects are miserably aligned and no structure is there.
Align the contents properly and enclose them within a card.

Some sample card designs are attached for reference.
Screenshot from 2020-02-12 19-31-21
Screenshot from 2020-02-12 19-31-07

### PR DESCRIPTION
**Pull request by blaze-assault**
__370__ 

Fixes #370

#### Short description of what this resolves:
added cards in projects section

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/Opencode-Collaborative-20abc/
@Jigar3 please review

**Comment by thesmallstar** [comment]
image
 Can you add some padding here?

**Comment by blaze-assault** [comment]
On top??

**Comment by Jigar3** [comment]
@blaze-assault atleast make the project name in bold to distinguish between name and description

**Pull request closed without merging**
