### PR TITLE
Added default image

### LINKED ISSUE #286: Load any default image in participants section on error
2 errors possible Error:
1. No image given
2. Image not found

### PR DESCRIPTION
**Pull request by starboi02**
__286__ 

Fixes #286 

#### Short description of what this resolves:

Added default image

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by starboi02** [comment]
@thesmallstar https://starboi02.github.io/

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by abhishekmsingh** [comment]
@starboi02 due to some internal error your pr merge will take time.

**Comment by thesmallstar** [comment]
Can you check your live link? Seems weird
sorry for the late response, was busty.

**Comment by starboi02** [comment]
Sir, it looks normal now. If anything's wrong ,please clarify it.

**Comment by starboi02** [comment]
@thesmallstar please review

**Comment by thesmallstar** [comment]
Great Work!

**Pull request merged**
