### PR TITLE
Jsgame

### PR DESCRIPTION
**Pull request by prince-7**
__266__ 

Fixes #266

#### Short description of what this resolves:
Made a js game

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Jigar3** [comment]
@prince-7 Live Link?

**Comment by prince-7** [comment]
https://prince-7.github.io/

**Comment by prince-7** [comment]
> @prince-7 Live Link?

https://prince-7.github.io/

**Comment by Jigar3** [comment]
Resolve conflicts and edit only games.md

**Pull request closed without merging**
