### PR TITLE
Participants Cards

### LINKED ISSUE #372: Edit Participation Section
The current participation section is not at all aligned and has no structure. Beautify it by making cards for every participant.

### PR DESCRIPTION
**Pull request by pradhuman1**
__372__ 

Fixes #372 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-https://pradhuman1.github.io/Opencode-Collaborative-20/
-

### CODE REVIEW

**Comment by Jigar3** [comment]
The cards aren't looking nice at all. Use https://github.com/opencodeiiita/Opencode-Collaborative-20/pull/399 this as your card structure

**Comment by pradhuman1** [comment]
@Jigar3 please review now

**Comment by Jigar3** [comment]
Still its the same. You may use https://github.com/opencodeiiita/Opencode-Collaborative-20/pull/398
 https://jealous-pig.surge.sh/ this. It looks really nice

**Comment by pradhuman1** [comment]
@Jigar3 i changed cards now please review

**Comment by Jigar3** [comment]
Change the heading to "Participants" align it in center and adding some padding in the top of heading

**Comment by pradhuman1** [comment]
@Jigar3 please review

**Comment by Jigar3** [comment]
remove conflicts

**Comment by pradhuman1** [comment]
@Jigar3 conflicts resolved

**Pull request merged**
