### PR TITLE
Js game

### PR DESCRIPTION
**Pull request by prince-7**
__266__ 

Fixes #266

#### Short description of what this resolves:
Java Script Game Created

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by thenullterminator** [comment]
@prince-7 resolve conflicts and squash

**Comment by prince-7** [comment]
conflict resolved

**Comment by thesmallstar** [comment]
image

why is this file changed?

**Comment by prince-7** [comment]
that changed file has been deleted, please review the JS game file

**Comment by thesmallstar** [comment]
image
 still

**Pull request closed without merging**
